In [29]:
import numpy as np
import os, cv2

root = r"C:\Users\KIIT\Tensorflow\Face_mask_detection\dataset"

# cateogries {1: with_mask, 2: without_mask}
categories = os.listdir(root)
# Labels
labels = np.arange(2)

Organizing Data

In [30]:
dim = 100        # Dimmension (100 X100)
lablesCateogry = {'with_mask': 0, 'without_mask' : 1}

Data, Labels = [], []

for category in categories:
    root_sub_folder = os.path.join(root, category)
    images = os.listdir(root_sub_folder)
    
    for image in images:
        img_path = os.path.join(root_sub_folder, image)
        img = cv2.imread(img_path)
        
        # 1: RGB -> Gray scale
        # 2: Resize to (100 X 100) Dimmension
        grayMode_img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
        resized_img = cv2.resize(grayMode_img, (dim, dim))
        
        Data.append(resized_img)
        Labels.append(lablesCateogry[category])

In [31]:
# Data
Data

[array([[248, 248, 248, ..., 246, 246, 246],
        [248, 248, 248, ..., 246, 246, 246],
        [249, 249, 249, ..., 247, 247, 247],
        ...,
        [ 31,  43,  45, ...,  34,  27,  26],
        [ 36,  45,  46, ...,  35,  27,  27],
        [ 37,  45,  49, ...,  33,  26,  26]], dtype=uint8),
 array([[197, 192, 197, ..., 175, 191, 197],
        [196, 195, 177, ..., 138, 180, 197],
        [200, 191, 143, ...,  98, 157, 183],
        ...,
        [ 80, 148, 186, ..., 162, 187, 198],
        [113, 171, 192, ...,  99, 137, 176],
        [139, 189, 199, ...,  36,  73, 119]], dtype=uint8),
 array([[197, 129,  71, ...,  20,  18,  19],
        [185, 115,  62, ...,  22,  20,  20],
        [152,  87,  48, ...,  25,  23,  20],
        ...,
        [ 33,  30,  31, ...,  12,  13,  11],
        [ 33,  29,  32, ...,  12,  11,  11],
        [ 35,  27,  30, ...,  12,  12,  12]], dtype=uint8),
 array([[255, 255, 255, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255],
        [255, 25

In [32]:
# Labels
Labels

[1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,


In [33]:
print('Shape of Data', np.array(Data).shape)
print('Shape of Labels', np.array(Labels).shape)

Shape of Data (7553, 100, 100)
Shape of Labels (7553,)


Scaling Dataset

In [34]:
# data [List -> np.array]
Data = np.array(Data)/255.0
Data = np.reshape(Data, (Data.shape[0], dim, dim, 1))

# Labels [List -> np.array]
Labels = np.array(Labels)

In [35]:
print('Shape of Data', np.array(Data).shape)
print('Type of Data', type(Data))

print('Shape of Labels', np.array(Labels).shape)
print('Type of Labels', type(Labels))

Shape of Data (7553, 100, 100, 1)
Type of Data <class 'numpy.ndarray'>
Shape of Labels (7553,)
Type of Labels <class 'numpy.ndarray'>


In [39]:
from keras.utils import np_utils
# Lables[uni-Dimmensional np.array -> bi-Dimmensional categorical numpy array(dtype = float32)]
Labels = np_utils.to_categorical(Labels)
Labels

array([[0., 1.],
       [0., 1.],
       [0., 1.],
       ...,
       [1., 0.],
       [1., 0.],
       [1., 0.]], dtype=float32)

In [40]:
# Categorical Labels
print('Shape of Labels', np.array(Labels).shape)
print('Type of Labels', type(Labels))

Shape of Labels (7553, 2)
Type of Labels <class 'numpy.ndarray'>


Save the Data and Labels as numpy array

In [41]:
# save DATA & LABELS 
np.save('Data', Data)
np.save('Labels', Labels)